version: "3.5"

services:
  user-database:
    image: postgres:10
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
    ports:
      - 5432:5432
    volumes:
      - "${PGDATA_DIR:-/var/lib/postgresql/farm/}:/var/lib/postgresql/data"
  user-api:
    container_name: user-api
    image: user-api
    network_mode: host
    build: userTask
    volumes:
      - .:/webapps
    ports:
      - "8000:8000"
    depends_on:
      - user-database

  user-unittests:
    image: user-api
    network_mode: host
    build: userTask
    volumes:
      - .:/webapps
    command: >
      sh -c "sleep 5
      && flake8
      && coverage erase
      && coverage3 run --source='.' manage.py test -v3 --noinput
      && coverage3 xml -i -o coverage/coverage-user.xml"
    depends_on:
      - user-database
